version: '3'

services:
    kf-task-release-reports:
        build: .
        image: kf-task-release-reports:latest
        command: /bin/ash -c "flask run"
        environment:
            - DYNAMO_ENDPOINT=http://dynamo:8050
    dynamo:
        image: amazon/dynamodb-local:latest
        ports:
            - "8050:8000"
